### PR TITLE
38 label coin

### PR DESCRIPTION
**Pull request by gbalabasquer**
@nmushegian 
- Removed rules field
- Added name, symbol and decimals fields.

We've used "string" for name and symbol fields. Basically because it was how we saw it in another example. Let me know if that is ok or we should use another type.

### CODE REVIEW

**Comment by nmushegian** [comment]
lgtm

**Comment by gbalabasquer** [comment]
@dbrock 
Could you take a look as well, please? Let me know and I'll merge it.

**Comment by dbrock** [comment]
Nice change, thank you for putting some thought into this

**Comment by gbalabasquer** [comment]
Thanks for you comments. Will merge it now.

**Pull request merged**
