### PR TITLE
prevent interacting with dangerous null values

### PR DESCRIPTION
**Pull request by rainbreak**
there's a better modifier name than 'zeroguard' but idk

### CODE REVIEW

**Comment by dbrock** [comment]
:+1:

How about `needs`?

**Comment by rainbreak** [comment]
¯_(ツ)_/¯

**Comment by nmushegian** [comment]
`nullguard`?

**Comment by rainbreak** [comment]
I actually changed it to `nullguard` but then decided that `zeroguard` looked better typographically :)

`nullguard` probably makes more sense though - not every null is a zero.

**Pull request merged**
